baseURL = "/"
languageCode = "en-gb"
title = "James Vibar, Web Designer / Developer"
googleAnalytics = "UA-115901002-2"

enableRobotsTXT = true
disableAliases = true

[params]
disallow_search_engines = false # set robots.txt to disallow everything
description = "UI/UX/WEB designer, developer."
keywords = "web designer, web developer, web design, site development, illustration"
logosvg = "logo"
headline = "James Vibar"
textline = "A frontend web designer/developer from the Philippines."
canonical = "https://www.jamesvibar.com/"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

