backend:
  name: git-gateway
  repo: jamesvibar/jamesvibar.com
  branch: master
  
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}