---
new_page_extension: md
auto_deploy: false
admin_path: "/static"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/works
  label: Works
  create: all
  match: "**/*"
upload_dir: src/images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
